export const categories = [
    { id: 'image-ai', name: 'Image AI', icon: '', count: 324, gradient: 'linear-gradient(135deg, #FF9A9E 0%, #FECFEF 100%)' },
    { id: 'text-ai', name: 'Text AI', icon: '', count: 215, gradient: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)' },
    { id: 'video-ai', name: 'Video AI', icon: '', count: 187, gradient: 'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)' },
    { id: 'audio-ai', name: 'Audio AI', icon: '', count: 142, gradient: 'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)' },
    { id: 'code-ai', name: 'Code AI', icon: '', count: 98, gradient: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)' },
    { id: 'business-ai', name: 'Business AI', icon: '', count: 156, gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)' },
];

export const tools = [
    {
        id: 'midjourney',
        name: 'Midjourney',
        slug: 'midjourney',
        description: 'Generates realistic images from natural language descriptions.',
        shortDescription: 'Advanced AI image generator.',
        category: 'image-ai',
        pricing: 'Paid',
        price: '$10/mo',
        rating: 4.8,
        views: '1.2M',
        logo: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNDgiIGZpbGw9IiM2MzY2ZjEiLz48dGV4dCB4PSI1MCIgeT0iNjUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSI0MCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5NSjwvdGV4dD48L3N2Zz4=',
        features: ['High resolution', 'Artistic styles', 'Discord community'],
        website: 'https://midjourney.com',
        addedDate: '2023-01-15',
        isFeatured: true,
        isTrending: true,
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        slug: 'chatgpt',
        description: 'A conversational AI model by OpenAI capable of understanding and generating human-like text.',
        shortDescription: 'The leading conversational AI chatbot.',
        category: 'text-ai',
        pricing: 'Freemium',
        price: '$20/mo',
        rating: 4.9,
        views: '5.4M',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
        features: ['Code generation', 'Creative writing', 'Q&A'],
        website: 'https://chat.openai.com',
        addedDate: '2022-11-30',
        isFeatured: true,
        isTrending: true,
    },
    {
        id: 'runway',
        name: 'Runway Gen-2',
        slug: 'runway',
        description: 'A multi-modal AI system that can generate novel videos with text, images, or video clips.',
        shortDescription: 'Text-to-video generation tool.',
        category: 'video-ai',
        pricing: 'Freemium',
        price: 'Free start',
        rating: 4.7,
        views: '850K',
        logo: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNDgiIGZpbGw9IiNmNTU3NmMiLz48dGV4dCB4PSI1MCIgeT0iNjUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSI0MCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5SMjwvdGV4dD48L3N2Zz4=',
        features: ['Text to Video', 'Image to Video', 'Inpainting'],
        website: 'https://runwayml.com',
        addedDate: '2023-06-01',
        isFeatured: true,
        isTrending: false,
    },
    {
        id: 'github-copilot',
        name: 'GitHub Copilot',
        slug: 'github-copilot',
        description: 'Your AI pair programmer. GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time.',
        shortDescription: 'AI pair programmer for coding.',
        category: 'code-ai',
        pricing: 'Paid',
        price: '$10/mo',
        rating: 4.8,
        views: '2.1M',
        logo: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        features: ['Code completion', 'Chat debugging', 'Multi-language'],
        website: 'https://github.com/features/copilot',
        addedDate: '2022-06-21',
        isFeatured: false,
        isTrending: true,
    }
];

export const stats = {
    totalTools: 1247,
    totalCategories: 47,
    lastUpdated: 'Today',
    freePercentage: '100%',
};
